// frontend/src/layouts/ProjectLayout.vue
<script setup lang="ts">
import { onMounted, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useProjectStore } from '@/stores/project'

const route = useRoute()
const project = useProjectStore()

async function load() {
  const id = route.params.id as string
  if (id) await project.fetchProject(id)
}

onMounted(load)
watch(() => route.params.id, load)
</script>

<template>
  <div class="project-layout">
    <router-view />
  </div>
</template>

<style scoped lang="scss">
.project-layout {
  min-height: 100%;
}
</style>

// frontend/src/layouts/ProjectLayout.tsx
import { useEffect } from "react";
import { Outlet, useParams } from "react-router-dom";
import { useProjectStore } from "@/stores/project";

export function ProjectLayout() {
  const { id } = useParams();
  const fetchProject = useProjectStore((s) => s.fetchProject);
  useEffect(() => {
    if (id) fetchProject(id);
  }, [id, fetchProject]);
  return (
    <div className="project-layout">
      <Outlet />
    </div>
  );
}
