// frontend/src/pages/AdminUserFormPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import * as usersApi from '@/api/users'
import GlButton from '@/components/ui/GlButton.vue'
import GlAlert from '@/components/ui/GlAlert.vue'

const route = useRoute()
const router = useRouter()
const isNew = computed(() => route.name === 'admin-user-new')
const error = ref('')

const form = ref({
  username: '',
  email: '',
  name: '',
  password: '',
  is_admin: false,
  state: 'active',
})

async function load() {
  if (isNew.value) return
  const u = await usersApi.getUser(route.params.id as string)
  form.value = {
    username: u.username,
    email: u.email,
    name: u.name,
    password: '',
    is_admin: u.is_admin,
    state: u.state,
  }
}

async function save() {
  error.value = ''
  try {
    if (isNew.value) {
      await usersApi.createUser({
        username: form.value.username,
        email: form.value.email,
        name: form.value.name,
        password: form.value.password,
        is_admin: form.value.is_admin,
      })
    } else {
      const body: usersApi.UpdateUserInput = {
        email: form.value.email,
        name: form.value.name,
        is_admin: form.value.is_admin,
        state: form.value.state,
      }
      if (form.value.password) body.password = form.value.password
      await usersApi.updateUser(route.params.id as string, body)
    }
    router.push({ name: 'admin-users' })
  } catch (e) {
    error.value = e instanceof Error ? e.message : '保存失败'
  }
}

onMounted(load)
</script>

<template>
  <div>
    <h1 class="page-title">{{ isNew ? '新建用户' : '编辑用户' }}</h1>
    <GlAlert v-if="error" variant="danger">{{ error }}</GlAlert>
    <form class="panel stack" @submit.prevent="save">
      <label v-if="isNew">用户名<input v-model="form.username" required /></label>
      <label>邮箱<input v-model="form.email" type="email" required /></label>
      <label>姓名<input v-model="form.name" /></label>
      <label>{{ isNew ? '密码' : '新密码（可选）' }}
        <input v-model="form.password" type="password" :required="isNew" />
      </label>
      <label v-if="!isNew">状态
        <select v-model="form.state">
          <option value="active">正常</option>
          <option value="blocked">已封禁</option>
        </select>
      </label>
      <label class="checkbox">
        <input v-model="form.is_admin" type="checkbox" />
        <span>
          <strong>管理员</strong>
          <span class="muted">可访问管理区域及全部项目</span>
        </span>
      </label>
      <div class="flex-between">
        <GlButton @click="router.back()">取消</GlButton>
        <GlButton variant="primary" type="submit">保存</GlButton>
      </div>
    </form>
  </div>
</template>

<style scoped lang="scss">
label.checkbox {
  flex-direction: row;
  align-items: flex-start;
  gap: 8px;

  .muted {
    display: block;
    font-weight: 400;
    font-size: 12px;
  }
}
</style>

// frontend/src/pages/AdminUserFormPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, Button, Checkbox, Form, Input, Select, Space } from 'antd'
import * as usersApi from '@/api/users'

export default function AdminUserFormPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const isNew = !id
  const [error, setError] = useState('')
  const [form] = Form.useForm()

  useEffect(() => {
    if (!isNew && id) {
      usersApi.getUser(id).then((u) => {
        form.setFieldsValue({
          username: u.username,
          email: u.email,
          name: u.name,
          is_admin: u.is_admin,
          state: u.state,
        })
      })
    }
  }, [id, isNew, form])

  async function onFinish(values: {
    username?: string
    email: string
    name: string
    password?: string
    is_admin: boolean
    state?: string
  }) {
    setError('')
    try {
      if (isNew) {
        await usersApi.createUser({
          username: values.username!,
          email: values.email,
          name: values.name,
          password: values.password!,
          is_admin: values.is_admin,
        })
      } else {
        const body: usersApi.UpdateUserInput = {
          email: values.email,
          name: values.name,
          is_admin: values.is_admin,
          state: values.state,
        }
        if (values.password) body.password = values.password
        await usersApi.updateUser(id!, body)
      }
      navigate('/admin/users')
    } catch (e) {
      setError(e instanceof Error ? e.message : '保存失败')
    }
  }

  return (
    <div>
      <h1 className="page-title">{isNew ? '新建用户' : '编辑用户'}</h1>
      {error && <Alert type="error" message={error} style={{ marginBottom: 16 }} />}
      <Form form={form} className="panel stack" layout="vertical" style={{ maxWidth: 560 }} onFinish={onFinish} initialValues={{ is_admin: false, state: 'active' }}>
        {isNew ? (
          <Form.Item label="登录名" name="username" rules={[{ required: true }]}>
            <Input placeholder="zhangsan" autoComplete="username" />
          </Form.Item>
        ) : (
          <Form.Item label="登录名">
            <div>@{form.getFieldValue('username')}</div>
          </Form.Item>
        )}
        <Form.Item label="邮箱" name="email" rules={[{ required: true, type: 'email' }]}>
          <Input autoComplete="email" />
        </Form.Item>
        <Form.Item label="显示名称" name="name">
          <Input placeholder="张三" />
        </Form.Item>
        <Form.Item label={isNew ? '密码' : '新密码（可选）'} name="password" rules={isNew ? [{ required: true }] : []}>
          <Input.Password autoComplete="new-password" />
        </Form.Item>
        {!isNew && (
          <Form.Item label="状态" name="state">
            <Select options={[{ value: 'active', label: '正常' }, { value: 'blocked', label: '已封禁' }]} />
          </Form.Item>
        )}
        <Form.Item name="is_admin" valuePropName="checked">
          <Checkbox>
            <strong>管理员</strong>
            <span className="muted" style={{ display: 'block', fontSize: 12 }}>可访问管理区域及全部项目</span>
          </Checkbox>
        </Form.Item>
        <Space>
          <Button onClick={() => navigate(-1)}>取消</Button>
          <Button type="primary" htmlType="submit">保存</Button>
        </Space>
      </Form>
    </div>
  )
}
