// frontend/src/pages/AdminDashboard.vue
<template>
  <div>
    <h1 class="page-title">管理概览</h1>
    <div class="panel">
      <p class="admin-intro">
        欢迎使用 Matrix 管理区域。在此管理用户、查看实例设置并监控平台访问。
      </p>
      <router-link to="/admin/users" class="admin-link">前往用户管理 →</router-link>
    </div>
  </div>
</template>

<style scoped lang="scss">
.admin-intro {
  margin: 0 0 var(--gl-spacing-3);
  line-height: 1.6;
  color: var(--gl-text-color-subtle);
}

.admin-link {
  font-weight: 600;
  font-size: var(--gl-font-size-sm);
}
</style>

// frontend/src/pages/AdminDashboard.tsx
import { Link } from 'react-router-dom'

export default function AdminDashboard() {
  return (
    <div>
      <h1 className="page-title">管理概览</h1>
      <div className="panel">
        <p style={{ margin: '0 0 12px', lineHeight: 1.6, color: 'var(--matrix-text-color-subtle)' }}>
          欢迎使用 Matrix 管理区域。在此管理用户、查看实例设置并监控平台访问。
        </p>
        <Link to="/admin/users" style={{ fontWeight: 600, fontSize: 14 }}>前往用户管理 →</Link>
      </div>
    </div>
  )
}
