// frontend/src/pages/AdminUsersPage.tsx
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Avatar, Button, Input, Modal, Space, Table, Tag } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import * as usersApi from '@/api/users'
import type { UserWithStats } from '@/api/users'
import { blockUser, resetUserPassword, unblockUser } from '@/api/admin'
import { avatarInitials } from '@/utils/avatar'

export default function AdminUsersPage() {
  const navigate = useNavigate()
  const [rows, setRows] = useState<UserWithStats[]>([])
  const [filter, setFilter] = useState('')
  const [deleteTarget, setDeleteTarget] = useState<UserWithStats | null>(null)
  const [resetTarget, setResetTarget] = useState<UserWithStats | null>(null)
  const [newPassword, setNewPassword] = useState('')

  const filtered = useMemo(() => {
    const q = filter.trim().toLowerCase()
    if (!q) return rows
    return rows.filter(
      (u) =>
        u.username.toLowerCase().includes(q) ||
        u.email.toLowerCase().includes(q) ||
        (u.name || '').toLowerCase().includes(q),
    )
  }, [filter, rows])

  async function load() {
    const res = await usersApi.listUsers()
    setRows(res.users)
  }

  useEffect(() => { load() }, [])

  async function confirmDelete() {
    if (!deleteTarget) return
    await usersApi.deleteUser(deleteTarget.id)
    setDeleteTarget(null)
    await load()
  }

  async function confirmReset() {
    if (!resetTarget || !newPassword) return
    await resetUserPassword(resetTarget.id, newPassword)
    setResetTarget(null)
    setNewPassword('')
  }

  async function toggleBlock(u: UserWithStats) {
    if (u.state === 'active') await blockUser(u.id)
    else await unblockUser(u.id)
    await load()
  }

  return (
    <div>
      <div className="flex-between">
        <h1 className="page-title">用户</h1>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => navigate('/admin/users/new')}>新建用户</Button>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
        <Input value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="搜索用户…" style={{ width: 320 }} />
        <span className="muted">共 {filtered.length} 位用户</span>
      </div>
      <Table dataSource={filtered} rowKey="id" pagination={{ pageSize: 20 }}>
        <Table.Column title="" width={48} render={(_, row: UserWithStats) => (
          <Avatar style={{ backgroundColor: '#fc6d26' }}>{avatarInitials(row.name || row.username)}</Avatar>
        )} />
        <Table.Column title="显示名称" dataIndex="name" />
        <Table.Column title="登录名" dataIndex="username" />
        <Table.Column title="邮箱" dataIndex="email" />
        <Table.Column title="项目数" dataIndex="project_count" />
        <Table.Column title="状态" render={(_, row: UserWithStats) => (
          <>
            <Tag color={row.state === 'active' ? 'success' : 'error'}>{row.state}</Tag>
            {row.is_admin && <Tag color="warning">管理员</Tag>}
          </>
        )} />
        <Table.Column title="上次登录" render={(_, row: UserWithStats) => (
          row.last_sign_in_at ? new Date(row.last_sign_in_at).toLocaleString() : '—'
        )} />
        <Table.Column title="操作" render={(_, row: UserWithStats) => (
          <Space>
            <Button type="link" onClick={() => navigate(`/admin/users/${row.id}`)}>编辑</Button>
            <Button type="link" onClick={() => setResetTarget(row)}>重置密码</Button>
            <Button type="link" onClick={() => toggleBlock(row)}>
              {row.state === 'active' ? '封禁' : '解封'}
            </Button>
            <Button type="link" danger onClick={() => setDeleteTarget(row)}>删除</Button>
          </Space>
        )} />
      </Table>
      <Modal open={!!deleteTarget} title="删除用户" onCancel={() => setDeleteTarget(null)} onOk={confirmDelete} okText="删除" okButtonProps={{ danger: true }}>
        确定删除用户 <strong>{deleteTarget?.username}</strong>？
      </Modal>
      <Modal open={!!resetTarget} title="重置密码" onCancel={() => setResetTarget(null)} onOk={confirmReset} okText="重置" okButtonProps={{ disabled: !newPassword }}>
        <Input.Password value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="新密码" />
      </Modal>
    </div>
  )
}

// frontend/src/pages/AdminUsersPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import * as usersApi from '@/api/users'
import type { UserWithStats } from '@/api/users'
import { blockUser, resetUserPassword, unblockUser } from '@/api/admin'
import GlButton from '@/components/ui/GlButton.vue'
import GlTable from '@/components/ui/GlTable.vue'
import GlBadge from '@/components/ui/GlBadge.vue'
import GlModal from '@/components/ui/GlModal.vue'
import GlAvatar from '@/components/ui/GlAvatar.vue'

const router = useRouter()
const rows = ref<UserWithStats[]>([])
const filter = ref('')
const deleteTarget = ref<UserWithStats | null>(null)
const resetTarget = ref<UserWithStats | null>(null)
const newPassword = ref('')

const columns = [
  { key: 'avatar', label: '' },
  { key: 'name', label: '姓名' },
  { key: 'username', label: '用户名' },
  { key: 'email', label: '邮箱' },
  { key: 'project_count', label: '项目数' },
  { key: 'state', label: '状态' },
  { key: 'last_sign_in_at', label: '上次登录' },
]

const filtered = computed(() => {
  const q = filter.value.trim().toLowerCase()
  if (!q) return rows.value
  return rows.value.filter(
    (u) =>
      u.username.toLowerCase().includes(q) ||
      u.email.toLowerCase().includes(q) ||
      (u.name || '').toLowerCase().includes(q),
  )
})

async function load() {
  const res = await usersApi.listUsers()
  rows.value = res.users
}

async function confirmDelete() {
  if (!deleteTarget.value) return
  await usersApi.deleteUser(deleteTarget.value.id)
  deleteTarget.value = null
  await load()
}

async function confirmReset() {
  if (!resetTarget.value || !newPassword.value) return
  await resetUserPassword(resetTarget.value.id, newPassword.value)
  resetTarget.value = null
  newPassword.value = ''
}

async function toggleBlock(u: UserWithStats) {
  if (u.state === 'active') {
    await blockUser(u.id)
  } else {
    await unblockUser(u.id)
  }
  await load()
}

function formatSignIn(iso?: string) {
  if (!iso) return '—'
  return new Date(iso).toLocaleString()
}

onMounted(load)
</script>

<template>
  <div>
    <div class="flex-between">
      <h1 class="page-title">用户</h1>
      <GlButton variant="primary" @click="router.push({ name: 'admin-user-new' })">新建用户</GlButton>
    </div>

    <div class="admin-toolbar">
      <input v-model="filter" class="gl-input admin-filter" placeholder="搜索用户…" />
      <span class="muted">共 {{ filtered.length }} 位用户</span>
    </div>

    <GlTable :columns="columns" :rows="filtered as unknown as Record<string, unknown>[]">
      <template #cell-avatar="{ row }">
        <GlAvatar :name="(row as UserWithStats).name || (row as UserWithStats).username" />
      </template>
      <template #cell-state="{ row }">
        <GlBadge :variant="(row as UserWithStats).state === 'active' ? 'success' : 'danger'">
          {{ (row as UserWithStats).state }}
        </GlBadge>
        <GlBadge v-if="(row as UserWithStats).is_admin" variant="warning" style="margin-left: 4px">
          管理员
        </GlBadge>
      </template>
      <template #cell-last_sign_in_at="{ row }">
        {{ formatSignIn((row as UserWithStats).last_sign_in_at) }}
      </template>
      <template #actions="{ row }">
        <GlButton variant="link" @click="router.push({ name: 'admin-user-edit', params: { id: (row as UserWithStats).id } })">
          编辑
        </GlButton>
        <GlButton variant="link" @click="resetTarget = row as UserWithStats">重置密码</GlButton>
        <GlButton variant="link" @click="toggleBlock(row as UserWithStats)">
          {{ (row as UserWithStats).state === 'active' ? '封禁' : '解封' }}
        </GlButton>
        <GlButton variant="link" @click="deleteTarget = row as UserWithStats">删除</GlButton>
      </template>
    </GlTable>

    <GlModal :open="!!deleteTarget" title="删除用户" @close="deleteTarget = null">
      <p>确定删除用户 <strong>{{ deleteTarget?.username }}</strong>？</p>
      <template #footer>
        <GlButton @click="deleteTarget = null">取消</GlButton>
        <GlButton variant="danger" @click="confirmDelete">删除</GlButton>
      </template>
    </GlModal>

    <GlModal :open="!!resetTarget" title="重置密码" @close="resetTarget = null">
      <label>新密码<input v-model="newPassword" type="password" class="gl-input" /></label>
      <template #footer>
        <GlButton @click="resetTarget = null">取消</GlButton>
        <GlButton variant="primary" :disabled="!newPassword" @click="confirmReset">重置</GlButton>
      </template>
    </GlModal>
  </div>
</template>

<style scoped lang="scss">
.admin-toolbar {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
}

.admin-filter {
  width: min(320px, 100%);
}
</style>
