// frontend/src/pages/NotFoundPage.vue
<template>
  <div class="panel not-found">
    <h1 class="page-title">404</h1>
    <p class="muted">页面不存在。</p>
    <router-link to="/projects">返回项目列表</router-link>
  </div>
</template>

<style scoped lang="scss">
.not-found {
  max-width: 480px;
  margin: 48px auto;
  text-align: center;
}
</style>

// frontend/src/pages/NotFoundPage.tsx
import { Link } from 'react-router-dom'

export default function NotFoundPage() {
  return (
    <div className="panel not-found" style={{ maxWidth: 480, margin: '48px auto', textAlign: 'center' }}>
      <h1 className="page-title">404</h1>
      <p className="muted">页面不存在。</p>
      <Link to="/projects">返回项目列表</Link>
    </div>
  )
}
