// frontend/src/pages/ProjectNewPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import * as projectsApi from '@/api/projects'
import type { ProjectVisibility } from '@/api/projects'
import GlButton from '@/components/ui/GlButton.vue'
import GlAlert from '@/components/ui/GlAlert.vue'

const router = useRouter()
const error = ref('')
const loading = ref(false)

const form = ref({
  name: '',
  git_url: '',
  git_branch: 'main',
  visibility: 'private' as ProjectVisibility,
})

const visibilityOptions: { value: ProjectVisibility; label: string; hint: string }[] = [
  { value: 'private', label: '私有', hint: '仅被明确授权的用户可访问。' },
  { value: 'internal', label: '内部', hint: '所有已登录用户可访问。' },
  { value: 'public', label: '公开', hint: '所有已登录用户可访问。' },
]

async function create() {
  error.value = ''
  loading.value = true
  try {
    const p = await projectsApi.createProject({
      name: form.value.name,
      git_url: form.value.git_url || undefined,
      git_branch: form.value.git_branch || undefined,
      visibility: form.value.visibility,
    })
    router.push(`/projects/${p.id}`)
  } catch (e) {
    error.value = e instanceof Error ? e.message : '创建项目失败'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="new-project">
    <h1 class="page-title">创建新项目</h1>
    <GlAlert v-if="error" variant="danger">{{ error }}</GlAlert>
    <form class="panel stack new-project__form" @submit.prevent="create">
      <div>
        <label class="gl-label" for="name">项目名称</label>
        <input id="name" v-model="form.name" class="gl-input" required placeholder="my-awesome-project" />
      </div>
      <div>
        <label class="gl-label" for="git">Git 地址（可选）</label>
        <input id="git" v-model="form.git_url" class="gl-input" placeholder="https://gitlab.example.com/group/project.git" />
      </div>
      <div>
        <label class="gl-label" for="branch">默认分支</label>
        <input id="branch" v-model="form.git_branch" class="gl-input" placeholder="main" />
      </div>
      <fieldset class="visibility-fieldset">
        <legend class="gl-label">可见性</legend>
        <label v-for="opt in visibilityOptions" :key="opt.value" class="visibility-option">
          <input v-model="form.visibility" type="radio" :value="opt.value" />
          <span>
            <strong>{{ opt.label }}</strong>
            <span class="muted">{{ opt.hint }}</span>
          </span>
        </label>
      </fieldset>
      <div class="flex-between">
        <GlButton type="button" @click="router.push('/projects')">取消</GlButton>
        <GlButton variant="primary" type="submit" :disabled="loading || !form.name">
          {{ loading ? '创建中…' : '创建项目' }}
        </GlButton>
      </div>
    </form>
  </div>
</template>

<style scoped lang="scss">
.new-project__form {
  max-width: 560px;
}

.visibility-fieldset {
  border: 1px solid var(--gl-border-color-default);
  border-radius: var(--gl-radius);
  padding: var(--gl-spacing-3) var(--gl-spacing-4);
  margin: 0;
  background: var(--gl-background-color-subtle);

  legend {
    margin-bottom: var(--gl-spacing-2);
  }
}

.visibility-option {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: var(--gl-spacing-3);
  padding: var(--gl-spacing-2) 0;
  cursor: pointer;

  strong {
    display: block;
    font-size: var(--gl-font-size-sm);
  }

  .muted {
    font-size: var(--gl-font-size-sm);
  }
}
</style>

// frontend/src/pages/ProjectNewPage.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, Button, Form, Input, Radio, Space } from 'antd'
import * as projectsApi from '@/api/projects'
import type { ProjectVisibility } from '@/api/projects'

const visibilityOptions: { value: ProjectVisibility; label: string; hint: string }[] = [
  { value: 'private', label: '私有', hint: '仅被明确授权的用户可访问。' },
  { value: 'internal', label: '内部', hint: '所有已登录用户可访问。' },
  { value: 'public', label: '公开', hint: '所有已登录用户可访问。' },
]

export default function ProjectNewPage() {
  const navigate = useNavigate()
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function onFinish(values: {
    name: string
    git_url?: string
    git_branch?: string
    visibility: ProjectVisibility
  }) {
    setError('')
    setLoading(true)
    try {
      const p = await projectsApi.createProject({
        name: values.name,
        git_url: values.git_url || undefined,
        git_branch: values.git_branch || undefined,
        visibility: values.visibility,
      })
      navigate(`/projects/${p.id}`)
    } catch (e) {
      setError(e instanceof Error ? e.message : '创建项目失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="new-project">
      <h1 className="page-title">创建新项目</h1>
      {error && <Alert type="error" message={error} style={{ marginBottom: 16 }} />}
      <Form
        className="panel stack"
        layout="vertical"
        style={{ maxWidth: 560 }}
        initialValues={{ git_branch: 'main', visibility: 'private' }}
        onFinish={onFinish}
      >
        <Form.Item label="项目名称" name="name" rules={[{ required: true }]}>
          <Input placeholder="my-awesome-project" />
        </Form.Item>
        <Form.Item label="Git 地址（可选）" name="git_url">
          <Input placeholder="https://gitlab.example.com/group/project.git" />
        </Form.Item>
        <Form.Item label="默认分支" name="git_branch">
          <Input placeholder="main" />
        </Form.Item>
        <Form.Item label="可见性" name="visibility">
          <Radio.Group>
            <Space direction="vertical">
              {visibilityOptions.map((opt) => (
                <Radio key={opt.value} value={opt.value}>
                  <strong>{opt.label}</strong>
                  <span className="muted" style={{ marginLeft: 8 }}>{opt.hint}</span>
                </Radio>
              ))}
            </Space>
          </Radio.Group>
        </Form.Item>
        <div className="flex-between">
          <Button onClick={() => navigate('/projects')}>取消</Button>
          <Button type="primary" htmlType="submit" loading={loading}>创建项目</Button>
        </div>
      </Form>
    </div>
  )
}
