// frontend/src/pages/SignOutPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const router = useRouter()
const loading = ref(false)

onMounted(async () => {
  loading.value = true
  try {
    await auth.logout()
  } finally {
    loading.value = false
    router.replace({ name: 'sign-in' })
  }
})
</script>

<template>
  <p class="muted">{{ loading ? '退出中…' : '正在跳转…' }}</p>
</template>

// frontend/src/pages/SignOutPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'

export default function SignOutPage() {
  const logout = useAuthStore((s) => s.logout)
  const navigate = useNavigate()
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function run() {
      try {
        await logout()
      } finally {
        setLoading(false)
        navigate('/users/sign_in', { replace: true })
      }
    }
    run()
  }, [logout, navigate])

  return <p className="muted">{loading ? '退出中…' : '正在跳转…'}</p>
}
