// frontend/src/pages/project/SettingsRepositoriesPage.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Alert, Button, Checkbox, Form, Input, Space, Table, Tabs } from 'antd'
import * as reposApi from '@/api/repositories'
import type { Repository } from '@/api/repositories'
import { useSettingsTabNavigate } from '@/hooks/useSettingsTabNavigate'
import { settingsTabs } from '@/locales/zh-CN'

export default function SettingsRepositoriesPage() {
  const { id: projectId = '' } = useParams()
  const onSettingsTabChange = useSettingsTabNavigate(projectId)
  const [repos, setRepos] = useState<Repository[]>([])
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [form] = Form.useForm()

  async function load() {
    const res = await reposApi.listRepositories(projectId)
    setRepos(res.repositories)
  }

  useEffect(() => { load() }, [projectId])

  async function add(values: { name: string; git_url: string; git_branch: string; is_default: boolean }) {
    setError('')
    try {
      await reposApi.createRepository(projectId, values)
      form.resetFields()
      form.setFieldsValue({ git_branch: 'main', is_default: false })
      await load()
    } catch (e) {
      setError(e instanceof Error ? e.message : '添加失败')
    }
  }

  async function pull(r: Repository) {
    setMessage('')
    await reposApi.pullRepo(projectId, r.id)
    setMessage(`已拉取 ${r.name}`)
  }

  async function push(r: Repository) {
    setMessage('')
    await reposApi.pushRepo(projectId, r.id)
    setMessage(`已推送 ${r.name}`)
  }

  async function remove(r: Repository) {
    await reposApi.deleteRepository(projectId, r.id)
    await load()
  }

  return (
    <div>
      <Tabs
        activeKey="repositories"
        onChange={onSettingsTabChange}
        items={settingsTabs(projectId).map((tab) => ({ key: tab.key, label: tab.label }))}
        style={{ marginBottom: 16 }}
      />
      <h2>仓库</h2>
      {error && <Alert type="error" message={error} style={{ marginBottom: 16 }} />}
      {message && <Alert type="success" message={message} style={{ marginBottom: 16 }} />}
      <Form form={form} className="panel stack" layout="vertical" style={{ maxWidth: 560, marginBottom: 24 }} initialValues={{ git_branch: 'main', is_default: false }} onFinish={add}>
        <Form.Item label="名称" name="name" rules={[{ required: true }]}><Input /></Form.Item>
        <Form.Item label="Git 地址" name="git_url"><Input /></Form.Item>
        <Form.Item label="分支" name="git_branch"><Input /></Form.Item>
        <Form.Item name="is_default" valuePropName="checked"><Checkbox>设为默认仓库</Checkbox></Form.Item>
        <Button type="primary" htmlType="submit">添加仓库</Button>
      </Form>
      <Table dataSource={repos} rowKey="id" pagination={false}>
        <Table.Column title="名称" dataIndex="name" />
        <Table.Column title="Git 地址" dataIndex="git_url" />
        <Table.Column title="分支" dataIndex="git_branch" />
        <Table.Column title="默认" render={(_, row: Repository) => row.is_default ? '是' : ''} />
        <Table.Column title="操作" render={(_, row: Repository) => (
          <Space>
            <Button onClick={() => pull(row)}>拉取</Button>
            <Button onClick={() => push(row)}>推送</Button>
            <Button danger onClick={() => remove(row)}>删除</Button>
          </Space>
        )} />
      </Table>
    </div>
  )
}

// frontend/src/pages/project/SettingsRepositoriesPage.vue
<script setup lang="ts">
import { onMounted, ref, computed } from 'vue'
import { useRoute } from 'vue-router'
import * as reposApi from '@/api/repositories'
import type { Repository } from '@/api/repositories'
import GlButton from '@/components/ui/GlButton.vue'
import GlTable from '@/components/ui/GlTable.vue'
import GlAlert from '@/components/ui/GlAlert.vue'
import GlTabs from '@/components/ui/GlTabs.vue'
import { settingsTabs } from '@/locales/zh-CN'

const route = useRoute()
const projectId = route.params.id as string
const tabs = computed(() => settingsTabs(projectId))
const repos = ref<Repository[]>([])
const message = ref('')
const error = ref('')
const form = ref({ name: '', git_url: '', git_branch: 'main', is_default: false })

const columns = [
  { key: 'name', label: '名称' },
  { key: 'git_url', label: 'Git 地址' },
  { key: 'git_branch', label: '分支' },
  { key: 'is_default', label: '默认' },
]

async function load() {
  const res = await reposApi.listRepositories(projectId)
  repos.value = res.repositories
}

async function add() {
  error.value = ''
  try {
    await reposApi.createRepository(projectId, form.value)
    form.value = { name: '', git_url: '', git_branch: 'main', is_default: false }
    await load()
  } catch (e) {
    error.value = e instanceof Error ? e.message : '添加失败'
  }
}

async function pull(r: Repository) {
  message.value = ''
  await reposApi.pullRepo(projectId, r.id)
  message.value = `已拉取 ${r.name}`
}

async function push(r: Repository) {
  message.value = ''
  await reposApi.pushRepo(projectId, r.id)
  message.value = `已推送 ${r.name}`
}

async function remove(r: Repository) {
  await reposApi.deleteRepository(projectId, r.id)
  await load()
}

onMounted(load)
</script>

<template>
  <div>
    <GlTabs :tabs="tabs" />
    <h2>仓库</h2>
    <GlAlert v-if="error" variant="danger">{{ error }}</GlAlert>
    <GlAlert v-if="message" variant="success">{{ message }}</GlAlert>

    <form class="panel stack repo-form" @submit.prevent="add">
      <label>名称<input v-model="form.name" required /></label>
      <label>Git 地址<input v-model="form.git_url" /></label>
      <label>分支<input v-model="form.git_branch" /></label>
      <label><input v-model="form.is_default" type="checkbox" /> 设为默认仓库</label>
      <GlButton variant="primary" type="submit">添加仓库</GlButton>
    </form>

    <GlTable :columns="columns" :rows="repos as unknown as Record<string, unknown>[]">
      <template #cell-is_default="{ row }">{{ (row as Repository).is_default ? '是' : '' }}</template>
      <template #actions="{ row }">
        <GlButton @click="pull(row as Repository)">拉取</GlButton>
        <GlButton @click="push(row as Repository)">推送</GlButton>
        <GlButton variant="danger" @click="remove(row as Repository)">删除</GlButton>
      </template>
    </GlTable>
  </div>
</template>

<style scoped lang="scss">
.repo-form { max-width: 560px; margin-bottom: 24px; }
</style>
