// frontend/src/pages/project/SettingsIntegrationsPage.vue
<script setup lang="ts">
import { onMounted, ref, watch, computed } from 'vue'
import { useRoute } from 'vue-router'
import { useProjectStore } from '@/stores/project'
import { useProjectPermissions } from '@/composables/useProjectPermissions'
import { getIntegrations, saveIntegrations, type IntegrationSettings } from '@/api/projects'
import GlButton from '@/components/ui/GlButton.vue'
import GlAlert from '@/components/ui/GlAlert.vue'
import GlTabs from '@/components/ui/GlTabs.vue'
import GlForm from '@/components/ui/GlForm.vue'
import { settingsTabs } from '@/locales/zh-CN'

const route = useRoute()
const project = useProjectStore()
const { canManageSettings } = useProjectPermissions(() => project.current)
const error = ref('')
const message = ref('')
const mcpJson = ref('{}')

const form = ref<NonNullable<IntegrationSettings['model']>>({
  base_url: '',
  api_key: '',
  model: '',
  max_tokens: 8192,
})

const tabs = computed(() => settingsTabs(route.params.id as string))

async function load() {
  const s = await getIntegrations(route.params.id as string)
  if (s.model) {
    form.value = { ...form.value, ...s.model }
  }
  mcpJson.value = JSON.stringify(s.mcp_servers || {}, null, 2)
}

async function save() {
  error.value = ''
  message.value = ''
  try {
    let mcp_servers = {}
    if (mcpJson.value.trim()) {
      mcp_servers = JSON.parse(mcpJson.value)
    }
    await saveIntegrations(route.params.id as string, {
      model: form.value,
      mcp_servers,
    })
    message.value = '已保存'
  } catch (e) {
    error.value = e instanceof Error ? e.message : '保存失败'
  }
}

onMounted(load)
watch(() => route.params.id, load)
</script>

<template>
  <div v-if="canManageSettings">
    <GlTabs :tabs="tabs" />
    <h2>集成</h2>
    <p class="muted">项目级模型与 MCP 覆盖（留空则使用系统 YAML 默认）。</p>
    <GlAlert v-if="error" variant="danger">{{ error }}</GlAlert>
    <GlAlert v-if="message" variant="success">{{ message }}</GlAlert>
    <form class="panel stack" @submit.prevent="save">
      <GlForm label="模型 API 地址"><input v-model="form.base_url" class="gl-input" placeholder="https://api.deepseek.com" /></GlForm>
      <GlForm label="API Key"><input v-model="form.api_key" class="gl-input" type="password" /></GlForm>
      <GlForm label="模型名称"><input v-model="form.model" class="gl-input" placeholder="deepseek-chat" /></GlForm>
      <GlForm label="最大 Token"><input v-model.number="form.max_tokens" class="gl-input" type="number" /></GlForm>
      <GlForm label="MCP 服务（JSON）">
        <textarea v-model="mcpJson" class="gl-textarea" rows="8" />
      </GlForm>
      <GlButton variant="primary" type="submit">保存</GlButton>
    </form>
  </div>
  <GlAlert v-else variant="danger">您没有权限访问集成设置。</GlAlert>
</template>

// frontend/src/pages/project/SettingsIntegrationsPage.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Alert, Button, Form, Input, InputNumber, Tabs } from 'antd'
import { useProjectStore } from '@/stores/project'
import { useProjectPermissions } from '@/hooks/useProjectPermissions'
import { useSettingsTabNavigate } from '@/hooks/useSettingsTabNavigate'
import { getIntegrations, saveIntegrations, type IntegrationSettings } from '@/api/projects'
import { settingsTabs } from '@/locales/zh-CN'

export default function SettingsIntegrationsPage() {
  const { id = '' } = useParams()
  const projectStore = useProjectStore()
  const perms = useProjectPermissions(projectStore.current)
  const onSettingsTabChange = useSettingsTabNavigate(id)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [mcpJson, setMcpJson] = useState('{}')
  const [form] = Form.useForm()

  async function load() {
    const s = await getIntegrations(id)
    if (s.model) {
      form.setFieldsValue({ ...s.model })
    }
    setMcpJson(JSON.stringify(s.mcp_servers || {}, null, 2))
  }

  useEffect(() => { load() }, [id])

  async function onFinish(values: NonNullable<IntegrationSettings['model']>) {
    setError('')
    setMessage('')
    try {
      let mcp_servers = {}
      if (mcpJson.trim()) mcp_servers = JSON.parse(mcpJson)
      await saveIntegrations(id, { model: values, mcp_servers })
      setMessage('已保存')
    } catch (e) {
      setError(e instanceof Error ? e.message : '保存失败')
    }
  }

  if (!perms.canManageSettings) {
    return <Alert type="error" message="您没有权限访问集成设置。" />
  }

  return (
    <div>
      <Tabs
        activeKey="integrations"
        onChange={onSettingsTabChange}
        items={settingsTabs(id).map((tab) => ({ key: tab.key, label: tab.label }))}
        style={{ marginBottom: 16 }}
      />
      <h2>集成</h2>
      <p className="muted">项目级模型与 MCP 覆盖（留空则使用系统 YAML 默认）。</p>
      {error && <Alert type="error" message={error} style={{ marginBottom: 16 }} />}
      {message && <Alert type="success" message={message} style={{ marginBottom: 16 }} />}
      <Form form={form} className="panel stack" layout="vertical" initialValues={{ max_tokens: 8192 }} onFinish={onFinish}>
        <Form.Item label="模型 API 地址" name="base_url">
          <Input placeholder="https://api.deepseek.com" />
        </Form.Item>
        <Form.Item label="API Key" name="api_key">
          <Input.Password />
        </Form.Item>
        <Form.Item label="模型名称" name="model">
          <Input placeholder="deepseek-chat" />
        </Form.Item>
        <Form.Item label="最大 Token" name="max_tokens">
          <InputNumber min={1} style={{ width: '100%' }} />
        </Form.Item>
        <Form.Item label="MCP 服务（JSON）">
          <Input.TextArea rows={8} value={mcpJson} onChange={(e) => setMcpJson(e.target.value)} />
        </Form.Item>
        <Button type="primary" htmlType="submit">保存</Button>
      </Form>
    </div>
  )
}
