// frontend/src/pages/project/SettingsMembersPage.vue
<script setup lang="ts">
import { onMounted, ref, computed } from 'vue'
import { useRoute } from 'vue-router'
import { useProjectStore } from '@/stores/project'
import { useProjectPermissions } from '@/composables/useProjectPermissions'
import * as projectsApi from '@/api/projects'
import type { ProjectMember, MemberRole } from '@/api/projects'
import type { User } from '@/api/auth'
import GlTable from '@/components/ui/GlTable.vue'
import GlButton from '@/components/ui/GlButton.vue'
import GlAlert from '@/components/ui/GlAlert.vue'
import GlTabs from '@/components/ui/GlTabs.vue'
import GlAvatar from '@/components/ui/GlAvatar.vue'
import GlUserSearch from '@/components/ui/GlUserSearch.vue'
import MemberRoleSelect from '@/components/ui/MemberRoleSelect.vue'
import { settingsTabs } from '@/locales/zh-CN'

const route = useRoute()
const project = useProjectStore()
const { canManageMembers } = useProjectPermissions(() => project.current)

const members = ref<ProjectMember[]>([])
const username = ref('')
const selectedUser = ref<User | null>(null)
const role = ref<MemberRole>('developer')
const error = ref('')

const tabs = computed(() => settingsTabs(route.params.id as string))

const columns = [
  { key: 'avatar', label: '' },
  { key: 'name', label: '账号' },
  { key: 'role', label: '角色' },
  { key: 'created_at', label: '加入时间' },
]

async function load() {
  const res = await projectsApi.listMembers(route.params.id as string)
  members.value = res.members
}

function onSelectUser(user: User) {
  selectedUser.value = user
}

async function invite() {
  error.value = ''
  const name = username.value.trim()
  if (!name) return
  try {
    await projectsApi.addMember(route.params.id as string, {
      username: name,
      role: role.value,
    })
    username.value = ''
    selectedUser.value = null
    await load()
  } catch (e) {
    error.value = e instanceof Error ? e.message : '添加失败'
  }
}

async function changeRole(m: ProjectMember, newRole: MemberRole) {
  await projectsApi.updateMember(route.params.id as string, m.user_id, newRole)
  await load()
}

async function remove(m: ProjectMember) {
  await projectsApi.removeMember(route.params.id as string, m.user_id)
  await load()
}

onMounted(load)
</script>

<template>
  <div>
    <GlTabs :tabs="tabs" />
    <h2>项目成员</h2>
    <GlAlert v-if="error" variant="danger">{{ error }}</GlAlert>

    <div v-if="canManageMembers" class="panel stack invite-panel">
      <h3>邀请成员</h3>
      <p class="muted">按用户名、姓名或邮箱搜索。</p>
      <label>
        用户
        <GlUserSearch v-model="username" @select="onSelectUser" />
      </label>
      <p v-if="selectedUser" class="selected-user">
        已选择：<strong>{{ selectedUser.name || selectedUser.username }}</strong>
        (@{{ selectedUser.username }})
      </p>
      <label>
        角色
        <MemberRoleSelect v-model="role" show-hints />
      </label>
      <GlButton variant="primary" :disabled="!username.trim()" @click="invite">邀请</GlButton>
    </div>

    <GlTable :columns="columns" :rows="members as unknown as Record<string, unknown>[]">
      <template #cell-avatar="{ row }">
        <GlAvatar :name="(row as ProjectMember).name || (row as ProjectMember).username" />
      </template>
      <template #cell-name="{ row }">
        <div>{{ (row as ProjectMember).name || (row as ProjectMember).username }}</div>
        <div class="muted">@{{ (row as ProjectMember).username }}</div>
      </template>
      <template #cell-role="{ row }">
        <MemberRoleSelect
          v-if="canManageMembers"
          :model-value="(row as ProjectMember).role"
          @update:model-value="changeRole(row as ProjectMember, $event)"
        />
        <span v-else>{{ projectsApi.roleLabels[(row as ProjectMember).role] }}</span>
      </template>
      <template #cell-created_at="{ row }">
        {{ new Date((row as ProjectMember).created_at).toLocaleDateString() }}
      </template>
      <template #actions="{ row }">
        <GlButton
          v-if="canManageMembers"
          variant="link"
          @click="remove(row as ProjectMember)"
        >
          移除
        </GlButton>
      </template>
    </GlTable>
  </div>
</template>

<style scoped lang="scss">
.invite-panel {
  margin-bottom: 16px;
  max-width: 560px;
}

label {
  display: flex;
  flex-direction: column;
  gap: 6px;
  font-weight: 600;
}

.selected-user {
  font-size: 13px;
  margin: 0;
}
</style>

// frontend/src/pages/project/SettingsMembersPage.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Alert, AutoComplete, Avatar, Button, Form, Select, Spin, Table, Tabs } from 'antd'
import { useProjectStore } from '@/stores/project'
import { useProjectPermissions } from '@/hooks/useProjectPermissions'
import { useSettingsTabNavigate } from '@/hooks/useSettingsTabNavigate'
import { useUserSearch } from '@/hooks/useUserSearch'
import * as projectsApi from '@/api/projects'
import type { ProjectMember, MemberRole } from '@/api/projects'
import type { User } from '@/api/auth'
import { settingsTabs } from '@/locales/zh-CN'
import { avatarInitials } from '@/utils/avatar'

export default function SettingsMembersPage() {
  const { id = '' } = useParams()
  const projectStore = useProjectStore()
  const perms = useProjectPermissions(projectStore.current)
  const onSettingsTabChange = useSettingsTabNavigate(id)
  const [members, setMembers] = useState<ProjectMember[]>([])
  const [username, setUsername] = useState('')
  const [selectedUser, setSelectedUser] = useState<User | null>(null)
  const [role, setRole] = useState<MemberRole>('developer')
  const [error, setError] = useState('')
  const userSearch = useUserSearch(username, setUsername)

  async function load() {
    const res = await projectsApi.listMembers(id)
    setMembers(res.members)
  }

  useEffect(() => { load() }, [id])

  async function invite() {
    setError('')
    const name = username.trim()
    if (!name) return
    try {
      await projectsApi.addMember(id, { username: name, role })
      setUsername('')
      setSelectedUser(null)
      await load()
    } catch (e) {
      setError(e instanceof Error ? e.message : '添加失败')
    }
  }

  async function changeRole(m: ProjectMember, newRole: MemberRole) {
    await projectsApi.updateMember(id, m.user_id, newRole)
    await load()
  }

  async function remove(m: ProjectMember) {
    await projectsApi.removeMember(id, m.user_id)
    await load()
  }

  const roleOptions = projectsApi.memberRoleOptions.map((r) => ({
    value: r.value,
    label: `${r.label} — ${r.hint}`,
    title: r.hint,
  }))

  return (
    <div>
      <Tabs
        activeKey="members"
        onChange={onSettingsTabChange}
        items={settingsTabs(id).map((tab) => ({ key: tab.key, label: tab.label }))}
        style={{ marginBottom: 16 }}
      />
      <h2>项目成员</h2>
      {error && <Alert type="error" message={error} style={{ marginBottom: 16 }} />}
      {!perms.canManageMembers && !error && (
        <Alert type="info" message="您仅有查看权限。如需邀请或管理成员，请联系项目 Maintainer 或 Owner。" style={{ marginBottom: 16 }} />
      )}
      {perms.canManageMembers && (
        <div className="panel stack" style={{ maxWidth: 560, marginBottom: 16 }}>
          <h3>邀请成员</h3>
          <p className="muted">按登录名、显示名称或邮箱搜索。</p>
          <AutoComplete
            value={userSearch.query}
            options={userSearch.options}
            onSelect={(val) => userSearch.pick(val, setSelectedUser)}
            onSearch={userSearch.onSearchInput}
            placeholder="按登录名、显示名称或邮箱搜索"
            notFoundContent={userSearch.loading ? <Spin size="small" /> : null}
            style={{ width: '100%' }}
          />
          {selectedUser && (
            <p style={{ fontSize: 13, margin: 0 }}>
              已选择：<strong>{selectedUser.name || selectedUser.username}</strong> (@{selectedUser.username})
            </p>
          )}
          <Form.Item label="角色">
            <Select value={role} onChange={setRole} style={{ minWidth: 140 }} options={roleOptions} />
          </Form.Item>
          <Button type="primary" disabled={!username.trim()} onClick={invite}>邀请</Button>
        </div>
      )}
      <Table dataSource={members} rowKey="user_id" pagination={false}>
        <Table.Column title="" width={48} render={(_, row: ProjectMember) => (
          <Avatar style={{ backgroundColor: '#fc6d26' }}>{avatarInitials(row.name || row.username)}</Avatar>
        )} />
        <Table.Column title="账号" render={(_, row: ProjectMember) => (
          <>
            <div>{row.name || row.username}</div>
            <div className="muted">@{row.username}</div>
          </>
        )} />
        <Table.Column title="角色" render={(_, row: ProjectMember) => (
          perms.canManageMembers ? (
            <Select
              value={row.role}
              onChange={(r) => changeRole(row, r)}
              style={{ minWidth: 140 }}
              options={projectsApi.memberRoleOptions.map((r) => ({ value: r.value, label: r.label, title: r.hint }))}
            />
          ) : projectsApi.roleLabels[row.role]
        )} />
        <Table.Column title="加入时间" render={(_, row: ProjectMember) => (
          new Date(row.created_at).toLocaleDateString()
        )} />
        {perms.canManageMembers && (
          <Table.Column title="操作" render={(_, row: ProjectMember) => (
            <Button type="link" danger onClick={() => remove(row)}>移除</Button>
          )} />
        )}
      </Table>
    </div>
  )
}
